### ISSUE TITLE
Malwarebytes Browser Guard blocked the download from jbead.ch

### ISSUE THREAD

**Issue by Erbigimbi** [damianbrunold/jbead#3]
https://www.jbead.ch/   website is being flagged by malwarebytes.
![Website blocked due to suspicious content - TS scams, cryptojacking, browser hijack, and other possibly suspicious activities](https://user-images.githubusercontent.com/27553296/186336754-88c442d3-02dd-4c7b-8791-196d03db14e7.jpg)

Adguard app says it is safe.
Website jbead.ch is not present in the Yandex or Google Safe Browsing blacklists.

**Comment by damianbrunold** [comment]
It seems that Malwarebytes Browser Guard flags the download of the installation exe. Most probably this is due to the fact that the exe is not signed. Nonetheless, the file can be downloaded.

Long term, I will migrate JBead to a web app, thus obviating any installation on the local computer. If you want to take a peek at a pre-release, visit [www.texil-plattform.ch](https://www.textil-plattform.ch)
